name: Python CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install flake8

      - name: Python Lint
        run: |
          flake8 .